global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: uml-diagrams-monitoring
    metrics_path: /metrics
    static_configs:
      - targets: ["uml-diagrams-api:8001", "uml-diagrams-api:8002"]
        labels:
          instance: uml-diagrams-api
