FROM nginx

# /default.conf.template is used to create the default configuration file for the Nginx container.
# See at https://hub.docker.com/_/nginx
COPY uml_diagrams_api.conf /etc/nginx/templates/default.conf.template
