# Generated by Django 5.0.6 on 2024-09-03 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('view-only', 'View'), ('view-copy', 'View & Copy'), ('view-edit', 'View & Edit')], default='view-only', help_text='Permission level which diagram is shared with.', max_length=16, verbose_name='Permission level')),
                ('shared_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when diagram was shared.', verbose_name='Shared at')),
                ('diagram', models.ForeignKey(help_text='Diagram which is shared.', on_delete=django.db.models.deletion.CASCADE, to='diagrams.diagram')),
                ('shared_to', models.ForeignKey(help_text='User whom diagram is shared to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shared to')),
            ],
            options={
                'unique_together': {('shared_to', 'diagram')},
            },
        ),
    ]
