# Generated by Django 5.0.6 on 2024-11-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
        ('sharings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='shared_to',
            field=models.ForeignKey(blank=True, help_text='User whom diagram is shared to.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shared to'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('permission_level', 'view-only'), ('shared_to__isnull', True)), ('shared_to__isnull', False), _connector='OR'), name='shared_to_is_null_when_permission_level_is_not_view_only', violation_error_code='wrong_permission_level_for_null_shared_to_field', violation_error_message="The 'shared_to' field may only be empty if the 'permission_level' field is set to 'view-only' (View)."),
        ),
    ]
