server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://uml-diagrams-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: uml-diagrams-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 60s
        filters:
        - name: name
          values: [uml-diagrams-api, uml-diagrams-nginx, uml-diagrams-postgres]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
    pipeline_stages:
      - docker: {}
