{
 "title": "Access logs data",
 "description": "Dashbord over nginx & api access logs, provided by Loki",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests to api (api)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by() (count_over_time({service_name=\"uml-diagrams-api\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests to api per status code (nginx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status)\r\n(count_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n| request_uri=~\"^/api/.*\"\r\n|  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "% of 5xx requests (nginx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"uml-diagrams-nginx\"} | json | status >= 500 | __error__=\"\"[$__interval])) / \r\nsum(count_over_time({service_name=\"uml-diagrams-nginx\"} | json | __error__=\"\"[$__interval])) * 100",
     "legendFormat": "HTTP status: 500"
    }
   ]
  },
  {
   "title": "logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name) (bytes_over_time({service_name=~\".+\"}[$__interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name) (count_over_time({service_name=~\".+\"}[$__interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Realtime visitors (nginx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(sum by (remote_addr) (count_over_time({service_name=\"uml-diagrams-nginx\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Recent requests to api (nginx)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"uml-diagrams-nginx\"} \r\n| json \r\n| request_uri=~\"^/api/.*\"\r\n| line_format \"➡️ {{.status}} {{.request_method}} {{.request_uri}}\""
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.95,{service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n| unwrap request_time\r\n|  __error__=\"\"  [$__interval]) by (http_host)",
     "legendFormat": "95th percentile"
    },
    {
     "direction": "backward",
     "expr": "max by (host) (max_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n| unwrap request_time\r\n|  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (count_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json |\r\n__error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (http_host) (sum_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n| status=200\r\n| unwrap body_bytes_sent\r\n|  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (http_referer) (count_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n|  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\"\r\n| __error__=\"\" [15m])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json |  __error__=\"\" [15m])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (remote_addr) (count_over_time({service_name=\"uml-diagrams-nginx\"}\r\n| json\r\n|  __error__=\"\" [15m])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested api URLs",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (request_uri) (count_over_time({service_name=\"uml-diagrams-nginx\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml`\r\n| json\r\n| status = 200 and request_uri =~ \"^/api/.*\"\r\n| __error__=\"\" [15m])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}