{
 "title": "Prometheus metrics (LTES)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "ℹ️ Общая информация", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "О дашборде:",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "Дашборд построен на основе метрик, собираемых с использованием `django-prometheus`.\n\nСтруктура дашборда включает 4 основных раздела с соответствующими панелями:\n\n- **Latency** – показатели задержек обработки запросов;\n- **Traffic** – метрики трафика и нагрузки;\n- **Errors** – информация о возникших ошибках;\n- **Saturation** – уровень загрузки и использование ресурсов."
   }
  },
  {
   "title": "FAQ по некоторым настройкам панелей:",
   "type": "text",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "options": {
    "content": "### 1. Функции: примеры\n\n| Функция                     | Что делает?                                                                           | Применение                                                                                                                |\n| --------------------------- | ------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------- |\n| `rate(metric[5m])`          | Усреднённая скорость изменения за последние 5 минут                                   | **RPS, скорость роста ошибок, нагрузка на сервис.**                                                                        |\n| `increase(metric[5m])`      | Вычисляет общее увеличение метрики за последние 5 минут                             | **Общее количество запросов, ошибок за период, увеличение значения метрики.**                                              |\n| `irate(metric[5m])`         | Мгновенная скорость роста (по двум последним точкам)                                  | **Для очень частых обновлений (high-resolution метрики).**                                                                 |\n| `delta(metric[5m])`         | Вычисляет разницу между первым и последним значением метрики за последние 5 минут     | **Изменение значения за короткий интервал, например, изменение температуры или нагрузки за небольшой промежуток времени.** |\n| `idelta(metric[5m])`        | Вычисляет изменение счетчика между двумя последними точками (показаниями) метрики     | **Для подсчёта количества событий за последний интервал времени, например, количества ошибок или запросов, произошедших за короткий промежуток времени.** |\n| `avg_over_time(metric[5m])` | Вычисляет среднее значение метрики за последние 5 минут                               | **Среднее значение запросов, задержек или других метрик за определённый интервал.**                                        |\n\n#### 1.1. Что делает функция `rate()`?\n\nФункция `rate(<expr>[$__rate_interval])` - вычисляет среднюю скорость увеличения (изменения) временного ряда в секунду (rate of increase) для указанного временного интервала.\n\nСкорость роста (изменения) счётчика в секунду за определённый временной интервал счиатется следущти образом:\n1. Берётся разницу значений метрики за указанный временной интервал.\n2. Эта разница делится на продолжительность интервала, чтобы получить изменение в секунду.\n\nЭто позволяет усреднить значение и учитывать только недавние изменения.\n\n>Особенности:\n>1. Прерывания монотонности (такие как сбросы счётчиков из-за перезапусков целевых систем) автоматически корректируются.\n>2. Расчёт экстраполируется на концы временного интервала, что позволяет учесть пропущенные запросы или несовпадение циклов сбора метрик с временным интервалом.\n\n#### 1.2. Что делает функция `delta()`?\n\nФункция `delta(<expr>[$__interval])` - вычисляет разницу между первым и последним значением каждого элемента временного ряда в указанном диапазоне, возвращая мгновенный вектор с рассчитанными разностями и соответствующими метками.\n\nЭто просто разница между двумя крайними точками в интервале, без учёта изменений, происходящих внутри интервала.\n\n>Особенности:\n>1. Разница экстраполируется на весь временной диапазон, как указано в селекторе диапазона, поэтому возможно получение нецелого значения, даже если все значения выборки являются целыми числами.\n\n#### 1.2. Что делает функция `increase()`?\n\nФункция `increase(<expr>[1h])` - вычисляет увеличение значения временного ряда за указанный интервал времени.\n\nЭта функция используется для счётчиков (`counters`), которые монотонно увеличиваются, например, количество запросов или ошибок, за исключением случаев сброса счётчика.\n\n>Особенности:\n>1. Разрывы в монотонности (например, сбросы счётчиков из-за перезапуска таргетов) корректируются автоматически.\n>2. Значение увеличения экстраполируется на весь указанный временной диапазон, поэтому можно получить нецелое значение, даже если счётчик увеличивается только целыми числами.\n\n### 2. Параметры запросов PromQL\n\n#### 2.1. Что такое `$__rate_interval`?\n\n`$__rate_interval` — это переменная, которая автоматически подставляет оптимальный интервал для `rate()` в зависимости от выбранного диапазона времени в дашборде.\n\nGrafana адаптирует её под размер окна, например:\n- Если выбрано `\"Last 15 min\"`, то `$__rate_interval` может быть `1m` (1 минута);\n- Если выбрано `\"Last 1h\"`, то `$__rate_interval` может быть `5m` (5 минут);\n- Для `\"Last 24h\"` — может быть `30m` или даже `1h`.\n\nАктуальное значение `$__rate_interval`, выбранное Grafana для панели можно посмотреть в настройках данной панели: **Query Inspector** → **Query** → 🔄 **Refresh**.\n"
   }
  },
  { "title": "⏳ Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "description": "Этот запрос вычисляет среднее время обработки запроса и различные перцентили времени отклика за определённый промежуток времени:\n1. Среднее время обработки запроса:\n    - `rate(django_http_requests_latency_including_middlewares_seconds_sum[$__rate_interval])` → вычисляет скорость изменения суммарного времени обработки запросов в секунду за указанный интервал.\n    - `rate(django_http_requests_latency_including_middlewares_seconds_count[$__rate_interval])` → вычисляет скорость изменения количества запросов в секунду за тот же интервал.\n    \n\tДеление этих двух значений даёт среднее время обработки запроса за указанный интервал времени.\n\n2. Перцентили времени отклика, использующие `histogram_quantile()` для анализа гистограммы времени отклика:\n    - `50`-й перцентиль (медиана) → показывает время отклика, быстрее которого выполняется `50%` запросов.\n    - `90`-й перцентиль → позволяет оценить задержки для `90%` пользователей.\n    - `95`-й перцентиль → помогает выявить запросы, испытывающие повышенные задержки (`5%` самых медленных).\n    - `99`-й перцентиль → отражает \"хвостовую\" задержку, с которой сталкивается `1%` пользователей.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "median (50th percentile)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum[$__rate_interval])\r\n/\r\nrate(django_http_requests_latency_including_middlewares_seconds_count[$__rate_interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "HTTP Request Latency by View [average and p95 (optional)]",
   "type": "timeseries",
   "description": "Этот запрос для каждого `view` (*без разбивки по HTTP-методам*) за определённый промежуток времени вычисляет:\n  - среднее время обработки запроса;\n  - `95`-ый перцентиль времени отклика запроса (*ступенчатый график, по умолчанию скрыт*). \n\nИспользуется скользящее среднее по `rate()`.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_sum[$__rate_interval])) by (view)\r\n/\r\nsum(rate(django_http_requests_latency_seconds_by_view_method_count[$__rate_interval])) by (view)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Latency by View and Method [average & p95]",
   "type": "timeseries",
   "description": "Этот запрос для каждого `view` и его HTTP-метода (`GET`, `POST` и т.д.) за определённый промежуток времени вычисляет:\n  - среднее время обработки запроса (*пунктирная линия*);\n  - `95`-ый перцентиль времени отклика запроса. \n\nИспользуется скользящее среднее по `rate()`.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[$__rate_interval])) by (le, method, view))",
     "legendFormat": "{{method}} {{view}}"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_sum[$__rate_interval])) by (method, view)\r\n/\r\nsum(rate(django_http_requests_latency_seconds_by_view_method_count[$__rate_interval])) by (method, view)",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  { "title": "📊 Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Current value of Requests per Second (RPS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_transport_total[$__rate_interval])",
     "legendFormat": "RPS: {{label_name}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second (RPS) ⏱️[1m averaged as default, 15s step]",
   "type": "timeseries",
   "description": "Этот запрос вычисляет количество HTTP-запросов в секунду (RPS) с учётом скользящего среднего за последний интервал в `1` минуту, с шагом `15` секунд по функции `rate()` или `irate()`:\n  - `rate(django_http_requests_total_by_transport_total[1m])` → вычисляет скорость изменения общего числа HTTP-запросов за интервал в `1` минуту, возвращая среднюю частоту запросов в секунду.\n  - `irate(django_http_requests_total_by_transport_total[1m])` → вычисляет мгновенную скорость изменения запросов, основываясь на последних двух точках данных, что полезно для краткосрочных пиков.\n\nМетрика отображает среднюю частоту входящих HTTP-запросов, поступающих в приложение, усреднённую за `1` минуту, с расчётом обновлений каждые `15` секунд.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_transport_total[$__rate_interval]) or irate(django_http_requests_total_by_transport_total[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests by Method",
   "type": "stat",
   "description": "Этот запрос выводит **общее количество запросов** для каждого HTTP-метода (например, `GET`, `POST`, `PUT`, `DELETE`) в Django:\n- **`django_http_requests_total_by_method_total`** — счётчик, который показывает количество запросов, обработанных сервером, агрегированное по HTTP-методам (например, `GET`, `HEAD`, `POST`, `PUT`, и т. д.).\n\nЗапрос отображает **общее количество запросов по каждому методу** за весь период наблюдения.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Requests in the Last Minute ⏱️[1m total]",
   "type": "barchart",
   "description": "Этот запрос вычисляет количество HTTP-запросов за последнюю минуту для каждого метода (`method`) в Django, используя `delta()`:\n- `delta(django_http_requests_total_by_method_total[1m])` → вычисляет разницу значений счетчика `django_http_requests_total_by_method_total` между началом и концом указанного интервала (`1m`), что соответствует количеству запросов за последнюю минуту для каждого метода.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 47 },
   "targets": [
    {
     "expr": "delta(django_http_requests_total_by_method_total[$__interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Hourly Request Changes",
   "type": "timeseries",
   "description": "Этот график отображает часовые изменения в общем количестве запросов, происходящих в течение последних `30` дней.\n\nДля расчёта изменений используется функция `delta()`, которая вычисляет разницу в запросах за `1` день, с шагом в `1` час.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "delta(django_http_requests_total_by_transport_total[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "🚨 Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Total HTTP Requests by Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total{status=~\"4..\"}",
     "legendFormat": "HTTP status: {{status}}"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=~\"2..|3..\"}",
     "legendFormat": "HTTP status: {{status}}"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=~\"5..\"}",
     "legendFormat": "HTTP status: {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Response Errors Over Time",
   "type": "timeseries",
   "description": "Этот запрос отслеживает динамику появления HTTP-ошибок клиентских (`4xx`) и серверных (`5xx`) ошибок за последний временной интервал:\n  - `idelta(django_http_responses_total_by_status_total{status=~\"4..|5..\"}[$__rate_interval])` → вычисляет изменение счетчика для ответов с кодами ошибок `4xx` и `5xx` за указанный интервал времени `$__rate_interval`;\n  - функция `idelta()` вычисляет разницу между двумя последними измерениями для каждого кода состояния, отражая частоту ошибок в заданный период.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 67 },
   "targets": [
    {
     "expr": "idelta(django_http_responses_total_by_status_total{status=~\"4..|5..\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "🔥 Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Mean CPU Utilization of Last 1m",
   "type": "stat",
   "description": "Этот запрос отображает процент использования CPU процессом за последнюю минуту, вычисленный как отношение изменения метрики `process_cpu_seconds_total` (время работы процессора для данного процесса) за последний интервал в `1` минуту, разделённое на `60` секунд.\n\nЭто позволяет понять, какой процент времени в минуту процесс использует CPU.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total[1m]) / 60s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual:" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "RAM:" }
   ]
  },
  {
   "title": "Process Uptime (Time Since Process Start)",
   "type": "stat",
   "description": "Запрос отображает время, прошедшее с момента старта процесса.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Эта панель отображает использование памяти процессом, включая виртуальную и резидентную память:\n  - виртуальная память (`process_virtual_memory_bytes`) → общий объём памяти, доступной процессу. Включает зарезервированную память, отображённые в память файлы (библиотеки, исполняемые файлы) и данные, выгруженные в swap.\n  - резидентная память (`process_resident_memory_bytes`) → фактический объём оперативной памяти (RAM), занятой процессом в данный момент, без учёта swap.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes",
     "legendFormat": "virtual (RAM, swap: HDD/SSD, reserved, memory-mapped files)"
    },
    { "expr": "process_resident_memory_bytes", "legendFormat": "RAM" }
   ]
  }
 ]
}