# Generated by Django 5.0.6 on 2024-06-26 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Diagram title')),
                ('json', models.JSONField(help_text='Diagram structure and properties in JSON format.', verbose_name='Diagram JSON')),
                ('description', models.TextField(blank=True, default='', verbose_name='Diagram description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contributor', models.ForeignKey(help_text='User who added this diagram to the database.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contributor')),
            ],
            options={
                'verbose_name': 'Diagram',
                'verbose_name_plural': 'Diagrams',
            },
        ),
    ]
